FROM mysql:latest

# Задаємо змінні середовища для MySQL
ENV MYSQL_ROOT_PASSWORD=root_password
ENV MYSQL_DATABASE=test_db
ENV MYSQL_USER=test_user
ENV MYSQL_PASSWORD=test_password

# Відкриваємо порт для з'єднання
EXPOSE 3306
