# Використовуємо образ Python  
FROM python:3

# Копіюємо файk з програмою у контейнер
COPY app.py /

# Встановлюємо залежності
RUN pip install flask

# Запускаємо програму при запуску контейнера
CMD ["python", "./app.py"]
